### ISSUE TITLE
Incorrect database link on vercel app

### ISSUE THREAD

**Issue by njk112** [jcha0713/astro-notion#3]
On the [vercel app](https://astro-notion.vercel.app/posts/Getting-Started-with-Astro-notion-abf4b8e913da4f78af2ab2360ea2c4c7) on the basic setup, point 4
```
Go to https://heliotrope-lavender-f03.notion.site/Example-Database-a845c6d59ead4034be1b637c6381073d 
and click duplicate on the upper right corner to use it as a template.
``` 
does not lead to the [database](https://heliotrope-lavender-f03.notion.site/Example-Database-a845c6d59ead4034be1b637c6381073d) and instead rerenders the vercel app page.

**Comment by jcha0713** [comment]
Thank you for reporting this!
I just updated it to a new link.

**Comment by jcha0713** [comment]
I'm going to close this since it's working now but feel free to comment if you don't think it's working correctly.
