### ISSUE TITLE
Could you provide boilerplate code for importing posts

### ISSUE THREAD

**Issue by Isaac-Tait** [jcha0713/astro-notion#5]
I am not familiar with Astro so I am unsure how to proceed with the boilerplate code to import the blog posts from my Notion Table into the `index.astro` file located in `src`. The [Notion docs](https://developers.notion.com/docs/create-a-notion-integration) has the code for `.js` not `.astro` so that will not work for this use case unfortunately. 

Thanks for putting this site together, it has a lot of promise!

[Here is my repo](https://github.com/Isaac-Tait/randomIdiocyBlog) of what I have so far...

**Comment by jcha0713** [comment]
Hi,

Sorry if the readme is not easy enough to follow. There's a [demo](https://github.com/jcha0713/astro-notion/tree/main/demo) project in this repo which is a minimal working version of astro-notion blog, so you might want to check that out. 

If you're not familiar with Astro, I recommend reading the [dynamic routes](https://docs.astro.build/en/core-concepts/routing/#dynamic-routes) section from the doc first, and then it'll be much easier to set things up.

Also please note that I'm (slowly) re-writing the library as there have been lots of updates in Astro.

Let me know if you have any other questions. Thanks!

**Comment by Isaac-Tait** [comment]
Thank you for your prompt reply @jcha0713 and suggestions too! It is starting to make a lot more sense now. Cheers! 😎
